# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d1e85f04efe165a4f694fc3ad4113fb5318352acbab49b0408cee6eba7f1284ed37ea14ff78774735de9dba7f2b9b8faf380c5a2d20b00372a1f59ab7690b07

test:
  secret_key_base: 39ac42917f1102930da370ffb7673f52e0883d6d61a150ff275812064e97559db82c96b140bae79ff3bc6c132133ff59352f8f102e6e879ed5c1281e8f590591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
